### ISSUE TITLE
Build failing on PHP 5.3

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/cron-command#1]
Failure:

```
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - symfony/filesystem 3.0.x-dev requires php >=5.5.9 -> your PHP version (5.3.29) does not satisfy that requirement.
    - symfony/filesystem 3.0.x-dev requires php >=5.5.9 -> your PHP version (5.3.29) does not satisfy that requirement.
    - Installation request for symfony/filesystem (locked at 3.0.x-dev) -> satisfiable by symfony/filesystem[3.0.x-dev].
```

From https://travis-ci.org/wp-cli/cron-command/jobs/205000328

**Comment by danielbachhuber** [comment]
@schlessera I *think* this is because the `composer.lock` file is committed to this project. It's not a problem on other projects because `composer.lock` isn't committed.

Thoughts on the best course to resolve?

**Comment by schlessera** [comment]
No, this has nothing to do with the presence of composer.lock.

Rather, you required `behat` without requiring a specific version of the Symfony components, that's why Composer pulled in Symfony v3. If you want the package to stay compatible to PHP 5.3, you'll have to manually force Symfony v2 components to be used by Behat. Behat should work with both.

**Comment by danielbachhuber** [comment]
> No, this has nothing to do with the presence of composer.lock.

Yep, it was `composer.lock`. See #2 and https://travis-ci.org/wp-cli/cron-command/jobs/205027559

**Comment by schlessera** [comment]
Yes, well removing `composer.lock` lets Travis build with versions that fit the system, yes. But it would also work with a `composer.lock` committed, if you would control the correct versions.

**Comment by schlessera** [comment]
That's not a pressing issue for now, though. At a later point, we will discuss how to handle versions across runtime requirements, phar building, Travis, etc...
