### ISSUE TITLE
Empty error message after action_scheduler_run_queue

### ISSUE THREAD

**Issue by ctekk7** [wp-cli/cron-command#101]
## Bug Report

[x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).
[x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

- **Describe the current, buggy behavior**

Empty errormessage after 'action_scheduler_run_queue' on 'wp cron event run --due-now'.
Success when 'action_scheduler_run_queue' is not run.

- **Describe how other contributors can replicate this bug**

I run "wp cron event run --due-now" on ubuntu 22.04.
If action_scheduler_run_queue was run then there is an empty error message.
If action_scheduler_run_queue isn't run, then there is a success message.

```js
Executed the cron event 'action_scheduler_run_queue' in 0.011s.
Error:
```

- **Describe what you would expect as the correct outcome**

Error message states what the error is.

- **Let us know what environment you are running this on**

```
OS:     Linux 5.15.0-92-generic #102-Ubuntu SMP Wed Jan 10 09:33:48 UTC 2024 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php8.1
PHP version:    8.1.2-1ubuntu2.14
php.ini used:   /etc/php/8.1/cli/php.ini
MySQL binary:   /usr/bin/mysql
MySQL version:  mysql  Ver 15.1 Distrib 10.6.16-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /var/www/www.example.com
WP-CLI packages dir:
WP-CLI cache dir:       /home/user/.wp-cli/cache
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.9.0

```

**Comment by danielbachhuber** [comment]
Thanks for the report, @ctekk7.

As a heads up, `action_scheduler_run_queue` isn't a core cron event, so that's something specific to the system.

I took a quick grep of the codebase and I don't see anywhere `wp cron event run` would output an empty error message. Here's the corresponding section of code:

https://github.com/wp-cli/cron-command/blob/bc7e4bd2f441a5bb3b311e1419be2b05ed53146d/src/Cron_Event_Command.php#L281-L291

Maybe you have another cron event that is calling `WP_CLI::error()` in its callback? Can you share the results of `wp cron event list` ?

**Comment by ctekk7** [comment]
Sure, here is the list.
![cron-list](https://github.com/wp-cli/cron-command/assets/70662943/180c67fb-71f9-4577-b095-79ecb936c426)

**Comment by danielbachhuber** [comment]
> I don't think its another event this is calling the error as it also occurs if only action_scheduler_run_queue is run.
> Is there any way to debug this behaviour?

I don't have any great suggestions for further debugging off the top of my head, unfortunately. I think the problem is somewhere within your system, not WP-CLI itself.

**Comment by ctekk7** [comment]
okay lets close this one then.
