### ISSUE TITLE
Add --exec=<php-code> argument to wp cron event run

### ISSUE THREAD

**Issue by jcvignoli** [wp-cli/cron-command#104]
It may be useful to use the argument
`--exec=<php-code>`
when executing
`wp cron event run`

If using on the same local dev two different databases, one can't access both. But sending for example a
`define( 'FIRST_DB', true )`
would allow to switch from one db to the second.

**Comment by johnbillion** [comment]
How does your environment work for regular web requests? Does it choose the database based on the domain name or URL?

If so, you should be able to use the `--url` flag to route the cron request to the correct database.

**Comment by jcvignoli** [comment]
@johnbillion
I have one WP install with a wp-config.php that selects the database/dbusername/dbpassword according to various variables.
I have in that config file two different database/dbusername/dbpassword.
I have a cron that calls this WP for updating the two databases.
Unfortunately, I can only update one of the databases, since with wp cli I can't pass a specific var (constant or head).
Hope it clarifies.

**Comment by danielbachhuber** [comment]
Some version of this is easily achievable with the existing `--require=` argument. You can run whatever PHP code you want before WordPress loads, or at various points in the execution process.

See https://github.com/wp-cli/extension-command/issues/405#issuecomment-1954226505 and https://make.wordpress.org/cli/handbook/references/internal-api/wp-cli-add-hook/
