### ISSUE TITLE
`wp cron event run` includes files that aren't included by `wp-cron.php`

### ISSUE THREAD

**Issue by iandunn** [wp-cli/cron-command#26]
I created a `WP_Cron` job that called `list_files()`. When I executed it via `wp cron event run`, it worked fine, so I committed it. When it was later executed by `wp-cron.php`, there was a fatal error, because `list_files()` was undefined.

`list_files()` lives in `wp-admin/includes/file.php`, which is included by `wp cron event run`, but not by `wp-cron.php`. This seems like a bug to me; `wp cron event run` should not include any files that are not included by `wp-cron.php`.

Steps to reproduce:
1. Schedule a cron job from a front end file
1. Call `list_files()` from the job
1. Run it with `wp cron event run`, there shouldn't be any output to `STDERR`.
1. Run it with `wp-cron.php`, and you should see the error in `STDERR` or `debug.log`.

See [r43046-core](https://core.trac.wordpress.org/changeset/43046) and [r43059-core](https://core.trac.wordpress.org/changeset/43059) for an example.

**Comment by schlessera** [comment]
Right now, `wp cron event run` just loads the normal WordPress install and then proceeds to execute the command.

I agree that this behavior is unexpected, so adding something like `@when before_wp_load` (and potentially adding a full manual includes) might already do the trick.

However, this is a breaking change, and people building commands to be run on Cron jobs might have their commands then failing all of a sudden.

It is probably safer to achieve this via a flag, then. This makes the implementation non-trivial, though...

**Comment by danielbachhuber** [comment]
Ultimately, the underlying "problem" is that WP-CLI [executes as an admin context](https://make.wordpress.org/cli/handbook/implementation-details/#wp_admin), not a frontend context.

I don't think this particular issue is one worth fixing. The same issue could apply to a custom function you write for a WP-CLI command, and then try to use elsewhere in a frontend context. Ultimately, if you're using admin functions in a frontend context, you should make sure to `require_once` the corresponding file.

**Comment by iandunn** [comment]
> Ultimately, if you're using admin functions in a frontend context, you should make sure to require_once the corresponding file.

I don't disagree with that. It still seems problematic to me that I can't rely on `wp cron event run` to reliably reproduce the `wp-cron.php` environment, but I realize that it's not a trivial change, and that there are back-compat issues. I'm happy to chalk it up to technical debt, and just make sure I do a final test via `wp-cron.php` from now on.
