### ISSUE TITLE
Suggestion, add a --all flag to wp cron delete

### ISSUE THREAD

**Issue by janw-me** [wp-cli/cron-command#39]
Just a way to delete/clear all scheduled cron events.

**Comment by janw-me** [comment]
The workaroud I used was just clear the option (I know that's not foolproof if you use alternate crons)

Composability is nice mainly for `wp post` so you can do some pre filtering. Of if you want to run all wordfence crons or something like that.
Implementing a `--all` will not break that. It's just an extra function that's easier.

Also `wp cron event run --all` exists. Most of the `wp plugin *` and `wp transient *` have the `--all` flag.

**Comment by schlessera** [comment]
@swissspidy I don't think your workaround would work, as the `wp cron event delete` command only accepts a single hook. You'd have to combine this with `xargs` to run multiple delete commands instead.

This then brings us to the reason why we should have a change here either way, as we'd want to avoid unnecessarily running multiple instances of WP-CLI if it is pretty straight-forward to do so.

In this case, that would mean to either accept multiple `<hook>` arguments as a variadic argument, or to provide something like `--all` instead.

Given what we have with other commands, and to stay consistent, I'd even suggest providing both.

This is less about removing composability, as it is about making an input argument "expressive" enough. So we're not adding new functionality to `wp cron event delete`, we're ensuring that the `<hook>` argument can be used for any combination of hooks you might want to delete: one hook, multiple hooks, all hooks.

Does that make sense, especially as it relates to the project's philosophy?

**Comment by swissspidy** [comment]
Sure, it does 👍

**Comment by Mike-Hermans** [comment]
I'll be picking up this issue today.
