### ISSUE TITLE
PHP Warning:  date() expects parameter 2 to be long, string given

### ISSUE THREAD

**Issue by mcguffin** [wp-cli/cron-command#42]
- Multisite evironment (subdomains), some 600 websites
 - Cron runs every 30 min.
 - PHP throws a warning on every site:
```
PHP Warning:  date() expects parameter 2 to be long, string given in phar:///home/swilkens/bin/wp/vendor/wp-cli/cron-command/src/Cron_Event_Command.php on line 363
Warning: date() expects parameter 2 to be long, string given in phar:///home/swilkens/bin/wp/vendor/wp-cli/cron-command/src/Cron_Event_Command.php on line 363
PHP Warning:  date() expects parameter 2 to be long, string given in phar:///home/swilkens/bin/wp/vendor/wp-cli/cron-command/src/Cron_Event_Command.php on line 364
Warning: date() expects parameter 2 to be long, string given in phar:///home/swilkens/bin/wp/vendor/wp-cli/cron-command/src/Cron_Event_Command.php on line 364
```
 - Above warnings occur rougly ~3000 times in one cron run (all 600 sites)

### WP Cli environment

```
$ wp cli info
OS:	Linux ##NOT_DISCLOSED## 3.2.0-70-generic #105-Ubuntu SMP Wed Sep 24 19:49:16 UTC 2014 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php5
PHP version:	5.5.9-1ubuntu4.27
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	##NOT_DISCLOSED##
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.1.0
```

### Notes
 - Upgrading PHP is not an option

### My cron.sh
```bash
#!/bin/bash

PATH_TO_WORDPRESS="NOT_DISCLOSED/htdocs"
for URL in = $(/home/NOT_DISCLOSED/bin/wp site list --fields=url --format=csv --path="$PATH_TO_WORDPRESS")
do
	if [[ $URL == "http"* ]]; then
		echo "Run Cron for $URL"
		/home/NOT_DISCLOSED/bin/wp cron event run --all --due-now --url="$URL" --path="$PATH_TO_WORDPRESS"
	fi
done
```

**Comment by danielbachhuber** [comment]
Hi @mcguffin,

Thanks for the report. The error notice is coming from this line: https://github.com/wp-cli/cron-command/blob/6446237294d56218a57c88cc1963303b92f7962a/src/Cron_Event_Command.php#L363

It seems like you might have some bad user data. Any chance you might be able to track down what the data actually is?

**Comment by mcguffin** [comment]
Gotcha! There are rougly 3000 entries like these in the logfile:
```
Executed the cron event '1441835262' in 0s.
Executed the cron event '1441835263' in 0s.
Executed the cron event '1441835268' in 0s.
Executed the cron event '1441835270' in 0s.
...
```

I guess some plugin mixed up the function parameters when calling `wp_schedule_event()`... ;)
I'll investigate this further and get back once I got the naughty little rascal.

Besides this: any chance to get wp-cli to check the wp cron array for validity at some point...?

**Comment by danielbachhuber** [comment]
> I guess some plugin mixed up the function parameters when calling `wp_schedule_event()`... ;)

That seems like a likely candidate :)

> Besides this: any chance to get wp-cli to check the wp cron array for validity at some point...?

Potentially, although that could be a bit of a rabbit hole.

**Comment by danielbachhuber** [comment]
> although that could be a bit of a rabbit hole.

And it's almost better to catch these bugs as warnings so that you can track down and fix them, instead of having them fail silently.

**Comment by mcguffin** [comment]
> And it's almost better to catch these bugs as warnings so that you can track down and fix them, instead of having them fail silently.

Good point!  
Nothing left to do but closing the issue now...
Thanks for answering!

**Comment by danielbachhuber** [comment]
> Thanks for answering!

You're welcome :)

**Comment by mcguffin** [comment]
Just as a Post scriptum, if someone stumbles upon the same issue: The issue was caused by this [charming little wp core bug](https://core.trac.wordpress.org/ticket/33463).
Cheers!
