### ISSUE TITLE
Command to unschedule all events with a given hook

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/cron-command#48]
## Feature Request

WordPress 4.9 introduced the `wp_unschedule_hook()` function which unschedules all events with the given hook.

It would be handy if there was a corresponding WP-CLI command, possibly `wp cron event unschedule <hook>`.

**Comment by schlessera** [comment]
Yes, makes sense and I also agree with the naming. PRs welcome for this.

**Comment by schlessera** [comment]
Creating the new command entails:
- [ ] Adding a public method `unschedule` to the `Cron_Event_Command` class.
- [ ] Adding corresponding tests to the `features/cron-event.feature` file.
- [ ] Adding the command name to the `extra.commands` section of the `composer.json` file.
- [ ] Regenerating the README file.
