### ISSUE TITLE
wp cron event run --due-now --url="" says unknown --url parameter

### ISSUE THREAD

**Issue by KittMedia** [wp-cli/cron-command#57]
According to the [docs](https://developer.wordpress.org/cli/commands/cron/event/run/) I tried to use the following command:

```
wp cron event run --due-now --url=""
```

Even if the docs say that the global parameter `--url` can be used, this is not the case here. I get the following message:
```
Error: Parameter errors:
 unknown --url parameter
```

So it seems for me that there is no handy command to run cron events through a multisite since – as far as I know – you need the `--url` parameter to call the crons for every site inside the multisite.

**Comment by schlessera** [comment]
I can't replicate this, I assume there's a problem with your shell. You could for example verify the $IFS configuration.

![Image 2020-02-18 at 5 18 16 PM](https://user-images.githubusercontent.com/83631/74754947-ac60dd00-5272-11ea-8bbe-353e80cd62ab.png)

**Comment by KittMedia** [comment]
Oh, it seems that I missed a detail here, sorry for that. It just occurs if you use an alias, e. g.:

```
wp @all cron event run --due-now --url=""
```

My `$IFS` seems to be fine though:
```
$ printf "%s" "$IFS" | od -bc
0000000 040 011 012
             \t  \n
0000003
```
