### ISSUE TITLE
cron php

### ISSUE THREAD

**Issue by loraent** [wp-cli/cron-command#61]
Bonsoir j'aimerai mettre en place une tache cron pour mettre à jour mes stocks woocommerce par rapport a mon entrepot qui vends aux entreprises et mon site aux particuliers donc les stocks ce mélange le pourquoi une tache cron php me serait utile.j'ai deja programmer mon export de l'entrepot une fois par jour en url format csv et c'est cette fonction que je voudrai integrer une fois par jour à mon stock wordpress.

**Comment by danielbachhuber** [comment]
Hey there,

Sorry for the late reply on this!

Feel free to stop by the `#cli` channel on [WordPress.org](https://make.wordpress.org/chat/) Slack if you'd like help debugging further.
