### ISSUE TITLE
Running wp cron event run wp_site_health_scheduled_check issues requests which are blocked (401)

### ISSUE THREAD

**Issue by mic345** [wp-cli/cron-command#68]
**Bug checkboxes**

- [✅ ] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [✅] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

Running the command `wp cron event run wp_site_health_scheduled_check` issues a request to ` /wp-json/wp/v2/types/post?context=edit` which is than blocked (401).

Example:
```
$ wp cron event run wp_site_health_scheduled_check
Executed the cron event 'wp_site_health_scheduled_check' in 0.545s.
Success: Executed a total of 1 cron event.

$ tail /opt/bitnami/apache2/logs/access_log
...
::1 - - [25/Jun/2020:22:48:03 +0000] "POST /wp-cron.php?doing_wp_cron=1593125283.7101540565490722656250 HTTP/1.1" 200 -
::1 - - [25/Jun/2020:22:48:03 +0000] "GET /wp-json/wp/v2/types/post?context=edit HTTP/1.1" 401 127

```

**Describe how other contributors can replicate this bug**

1. install a vanilla wp
2. install the latest wp cli
3. run `wp cron event run wp_site_health_scheduled_check` 

**Describe what you would expect as the correct outcome**

I would expect two things:

1. Not to report `success` if any request returned anything other than 200, including async ajax requests.
2. The internal requests not to get blocked.

**Let us know what environment you are running this on**

```
$ wp cli info
OS:     Linux 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64
Shell:  /bin/bash
PHP binary:     /opt/bitnami/php/bin/php
PHP version:    7.3.17
php.ini used:   /opt/bitnami/php/etc/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /home/bitnami
WP-CLI packages dir:
WP-CLI global config:   /opt/bitnami/apps/wordpress/bin/wp-cli.yml
WP-CLI project config:
WP-CLI version: 2.4.0

$ wp core version
5.4.2
```

**Provide a possible solution**

We were digging in the code and I saw that `WP_Site_Health::get_test_rest_availability` uses `$_SERVER['PHP_AUTH_USER']` (class-wp-site-health.php:1839) and I'm guessing the cli cron does not set this info, but of course I may be wrong, as we didn't peek on the cli code. Anyway, just a place to start.

Take care and stay safe!
mic.

**Comment by danielbachhuber** [comment]
Cleaning up stale issues. Feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.
