### ISSUE TITLE
Apply `pre_get_ready_cron_jobs` filter to crons when `--due-now` is provided

### ISSUE THREAD

**Issue by josedumas** [wp-cli/cron-command#86]
https://github.com/wp-cli/cron-command/blob/136e5db4bc7b35b62417dd77258ce0ca73f23ad3/src/Cron_Event_Command.php#L431

Hi!

In this way we could use filters such as pre_get_ready_cron_jobs as it is being done in cron.php

Now:

$crons  = _get_cron_array();

I propose:

$crons = wp_get_ready_cron_jobs();

Thanks

**Comment by danielbachhuber** [comment]
@josedumas Thanks for the request!

It looks like `wp_get_ready_cron_jobs()` behaves a little differently than `_get_cron_array()` ([ref](https://core.trac.wordpress.org/browser/tags/6.1/src/wp-includes/cron.php#L1108)):

> Returns the results of _get_cron_array() limited to events ready to be run,
> ie, with a timestamp in the past.

`wp cron event list` shows _all_ cron events, not just those ready to run.

Can you share a bit more detail about the problem you'd like to solve with this change?

**Comment by josedumas** [comment]
Hi @danielbachhuber !

I'd like to use the pre_get_ready_cron_jobs (https://developer.wordpress.org/reference/hooks/pre_get_ready_cron_jobs/)) filter to put additional logic in handling the cron event array.
  It would be useful in the case of running with "wp cron run events --due-now"

Anyway I managed to make a function that returns the list of events processed by me and I pass it as an input parameter to wp cron run. It wasn't exactly what I wanted but it might work for me.

**Comment by danielbachhuber** [comment]
> I'd like to use the pre_get_ready_cron_jobs (https://developer.wordpress.org/reference/hooks/pre_get_ready_cron_jobs/)) filter to put additional logic in handling the cron event array.
> It would be useful in the case of running with "wp cron run events --due-now"

Makes sense! For this particular scenario, I'd be fine to apply the `pre_get_ready_cron_jobs` filter (or maybe even call `wp_get_ready_cron_jobs()` directly) when the `--due-now` flag is provided.

I've updated the issue title accordingly. Feel free to submit a pull request if you'd like!

**Comment by josedumas** [comment]
Created  PR https://github.com/wp-cli/cron-command/pull/87

Thanks !
